#madlibs game
adjective1 = input()
noun1 = input()
adjective2 = input()
verb1 = input()
adjective3 = input()
print(f"Today I went to a {adjective1} zoo.")
print(f"In an exhibit I saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")